runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /assets/image
  static_dir: assets/image

- url: /assets/styles
  static_dir: assets/styles

- url: /(.+\.css)
  static_files: assets/styles/\1
  upload: assets/styles/(.+\.css)

- url: /(.+\.html)
  static_files: \1
  upload: (.+\.html)

- url: /(.+\.js)
  static_files: \1
  upload: (.+\.js)
