name: Workflow B

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true

jobs:
  invoke_workflow_a:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

    #   - name: Call Workflow A
        # uses: ./.github/workflows/workflow-a.yml@main
          
      - name: Access TAG from Workflow A
        run: |
            echo "TAG=${{ github.event.inputs.tag }}" >> "$GITHUB_ENV"
            echo "Fetching TAG from Workflow A"
            echo "TAG from Workflow A: $TAG"

      - name: Use TAG
        run: |
          echo "Using TAG: $TAG"
